In [1]:
# Some more magic so that the notebook will reload external python modules;
# see http://stackoverflow.com/questions/1907993/autoreload-of-modules-in-ipython
from Submission.Code.LR_Template import *
%load_ext autoreload
%autoreload 2

In [2]:
X_train, y_train, X_valid, y_valid, X_test = load_data(return_numpy=True, debug=True)

IOPub data rate exceeded.
The notebook server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--NotebookApp.iopub_data_rate_limit`.

Current values:
NotebookApp.iopub_data_rate_limit=1000000.0 (bytes/sec)
NotebookApp.rate_limit_window=3.0 (secs)



['and', 'but', 'for', 'in', 'is', 'it', 'on', 'the', 'this', 'to']


In [3]:
W = np.arange(0,10).reshape(-1, 1)
np_X_train = X_train.toarray()

np_scores = np_X_train.dot(W)
scores = X_train.dot(W)
print(f'difference: {np.sum(np_scores.sum() - scores.sum())}')

difference: 0


In [4]:
def logreg_loss(X, W, y):
    y = y.reshape(-1, 1)
    
    Z = X.dot(W)
    A = 1 / (1 + np.exp(Z))
    dW = (X_train.T).dot(A - y) / X.shape[0]
    loss = -(y * np.log(A) + (1 - y) * np.log(1 - A)).sum() / X.shape[0]

    return A, loss, dW

In [5]:
A, loss, dW = logreg_loss(X_train, W, y_train)
print(loss)

55.898386627411156


In [6]:
A, y_train

(array([[6.69285092e-03],
        [9.11051194e-04],
        [4.47377931e-38],
        ...,
        [1.97925988e-32],
        [3.30570063e-37],
        [5.00000000e-01]]),
 array([1, 1, 1, ..., 1, 1, 1]))

In [7]:
model = LogisticRegression(X_train.shape[1])
model.gradDescent(X_train, y_train, 0, 1)

array([0.69304327])

# Unbounded Vocab

In [8]:
X_train, y_train, X_valid, y_valid, X_test = load_data(return_numpy=True)

In [9]:
X_train.shape

(13193, 11103)

In [33]:
model = LogisticRegression(X_train.shape[1], reg = 1e-3)
loss_hist = model.gradDescent(X_train, y_train, 1, 200, verbose = True)
probs, y_pred = model.predict(X_valid)

print(score(y_valid, y_pred))
print(roc_auc_score(y_valid, y_pred))

Epoch :  99  loss :  0.3010379386135561
Epoch :  199  loss :  0.21414320086848054
[[ 263.  117.]
 [ 115. 2804.]]
0.9602739726027397
0.826354104686176


In [35]:
from sklearn.metrics import roc_auc_score

# Q3.1
probs, y_pred = model.predict(X_valid)
print(f'roc auc: {roc_auc_score(y_valid, y_pred)}')
probs, y_pred = model.predict(X_train)
print(f'roc auc: {roc_auc_score(y_train, y_pred)}')

roc auc: 0.826354104686176
roc auc: 0.8427889189505724


In [11]:
probs

array([[0.99993442],
       [0.80426203],
       [0.98934364],
       ...,
       [0.41885422],
       [0.99143391],
       [0.99856364]])

In [29]:
import numpy as np
from sklearn.metrics import roc_auc_score

for i in range(3):
    print(f'Test {i}: ')
    y_pred = None
    reg = np.random.uniform(0, 0.2)
    lr = np.random.uniform(1e-4, 1e-2)
    iterations = int(np.random.uniform(10, 500))
    
    print(f'regularization: {reg}')
    print(f'learning rate: {lr}')
    print(f'iterations: {iterations}')
    print('\n')
    model = LogisticRegression(X_train.shape[1], reg = reg)
    loss_hist = model.gradDescent(X_train, y_train, lr, iterations, verbose = False)
    probs, y_pred = model.predict(X_valid)
    
    if y_pred is None:
        print('-' * 40)
        continue
    
    print(f'f1 scores: {score(y_valid, y_pred)}')
    print(f'roc auc score: {roc_auc_score(y_valid, y_pred)}')
    print('-' * 40)

Test 0: 
regularization: 0.11460250372205912
learning rate: 0.0015336812182905552
iterations: 463


f1 scores: 0.9388871019620456
roc auc score: 0.5
----------------------------------------
Test 1: 
regularization: 0.07869200260163788
learning rate: 0.0024007930886685755
iterations: 273


f1 scores: 0.9388871019620456
roc auc score: 0.5
----------------------------------------
Test 2: 
regularization: 0.11239513376911235
learning rate: 0.0006469468857092667
iterations: 115


f1 scores: 0.9388871019620456
roc auc score: 0.5
----------------------------------------
